- name: Include OS dependent variables
  include_vars: "vars/{{ ansible_distribution }}.yaml"

- name: Install dependencies if required
  become: yes
  apt:
    name: "{{ vars['dependencies_' + ansible_distribution_major_version ] }}"
    state: present
