- name: Install OpenBoard on MacOS
  block:
    - name: Download .dmg file for MacOS
      get_url:
        url: "{{ item.browser_download_url }}"
        dest: "{{ playbook_dir }}/{{ item.name }}"
        force: yes
      register: openboard_installer_download
      when: '".dmg" in item.name'
      with_items: "{{ openboard_github_assets }}"

    - set_fact:
        openboard_installer_path: "{{ item.dest }}"
      when: item.dest is defined
      with_items: "{{ openboard_installer_download.results}}"
