- name: Add Xenial repositories
  become: yes
  copy:
    src: "{{ role_path }}/files/openboard.list"
    dest: /etc/apt/sources.list.d/
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16"

- name: Update the package database
  become: yes
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16"

- name: Install Openboard
  become: yes
  apt:
    deb: "{{ openboard_installer_path }}"
    state: present

- name: Fix broken dependencies
  become: yes
  apt:
    state: fixed
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16"

- name: Remove Xenial repositories
  become: yes
  file:
    path: /etc/apt/sources.list.d/openboard.list
    state: absent
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16"
