- name: Mount .dmg package
  command: "hdiutil attach ./{{ openboard_installer_path }} -nobrowse -mountpoint ./{{ openboard_github_repo }}"

- name: Extract the package content
  shell: cp -aR ./{{ openboard_github_repo }}/*.app /Applications/{{ openboard_github_repo }}.app

- name: Unmount the dmg package
  command: hdiutil detach ./{{ openboard_github_repo }}/

- name: Remove all the temporary files
  command: rm -R ./tmp/
